all:clean lexcmp lencmp digcmp loopcmp
lexcmp:
	gcc -o lexcmp lexcmp.c -Wall
lencmp:
	gcc -o lencmp lencmp.c -Wall
digcmp:
	gcc -o digcmp digcmp.c -Wall
loopcmp:
	gcc -o loopcmp loopcmp.c -Wall
	
clean: 
	rm -f lexcmp.o lexcmp
	rm -f lencmp.o lencmp
	rm -f digcmp.o digcmp
	rm -f loopcmp.o loopcmp	
