all:clean lexcmp lencmp digcmp loopcmp
prog1:
	gcc -o lexcmp lexcmp.c -Wall
prog2:
	gcc -o lencmp lencmp.c -Wall
prog3:
	gcc -o digcmp digcmp.c -Wall
prog4:
	gcc -o loopcmp loopcmp.c -Wall
	
clean: 
	rm -f lexcmp.o lexcmp
	rm -f lencmp.o lencmp
	rm -f digcmp.o digcmp
	rm -f loopcmp.o loopcmp	
