all:clean prog1 prog2 prog3 prog4
prog1:
	gcc -o prog1 lexcmp.c
prog2:
	gcc -o prog2 lencmp.c
prog3:
	gcc -o prog3 digcmp.c
prog4:
	gcc -o prog4 loopcmp.c
	
clean: 
	rm -f lexcmp.o prog1
	rm -f lencmp.o prog2
	rm -f digcmp.o prog3
	rm -f loopcmp.o prog4	
